name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25, 26]
        elixir: [1.14]

    env:
      MIX_ENV: test
      ImageOS: ubuntu20 # equivalent to runs-on ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
          otp-version: ${{matrix.otp}} # Define the OTP version [required]

      - uses: actions/cache@v4
        id: deps-cache
        with:
          path: |
            deps
            flame_k8s/deps
            flame_k8s_controller/deps
            flame_example/deps
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-

      - uses: actions/cache@v4
        id: build-cache
        with:
          path: |
            _build
            flame_k8s/_build
            flame_k8s_controller/_build
            flame_example/_build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master

      - name: Test cluster !
        run: kubectl get pods -A

      - name: Install dependencies and compile flame_k8s
        run: |
          cd flame_k8s
          mix deps.get
          mix compile
          cd ..

      - name: Install dependencies and compile flame_k8s_controller
        run: |
          cd flame_k8s_controller
          mix deps.get
          mix compile
          cd ..

      - name: Install dependencies and compile flame_example
        run: |
          cd flame_example
          mix deps.get
          mix compile
          cd ..

      - name: Run tests flame_k8s
        run: |
          cd flame_k8s
          MIX_ENV=test mix test
          cd ..

      - name: Run tests flame_k8s_controller
        run: |
          cd flame_k8s_controller
          MIX_ENV=test mix test
          cd ..

      - name: Run tests flame_example
        run: |
          cd flame_example
          MIX_ENV=test mix test
          cd ..
